%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/rolling/.*$
%global __requires_exclude_from ^/opt/ros/rolling/.*$

Name:           ros-rolling-mrpt2
Version:        2.9.2
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS mrpt2 package

License:        BSD
URL:            https://www.mrpt.org/
Source0:        %{name}-%{version}.tar.gz

Requires:       eigen3-devel
Requires:       freeglut-devel
Requires:       glfw-devel
Requires:       libXrandr-devel
Requires:       libXxf86vm-devel
Requires:       opencv-devel
Requires:       ros-rolling-cv-bridge
Requires:       ros-rolling-geometry-msgs
Requires:       ros-rolling-nav-msgs
Requires:       ros-rolling-octomap
Requires:       ros-rolling-rclcpp
Requires:       ros-rolling-rosbag2-storage
Requires:       ros-rolling-sensor-msgs
Requires:       ros-rolling-std-msgs
Requires:       ros-rolling-stereo-msgs
Requires:       ros-rolling-tf2
Requires:       ros-rolling-tf2-msgs
Requires:       suitesparse-devel
Requires:       ros-rolling-ros-workspace
BuildRequires:  assimp-devel
BuildRequires:  cmake
BuildRequires:  eigen3-devel
BuildRequires:  ffmpeg-devel
BuildRequires:  freeglut-devel
BuildRequires:  glfw-devel
BuildRequires:  jsoncpp-devel
BuildRequires:  libXrandr-devel
BuildRequires:  libXxf86vm-devel
BuildRequires:  libfreenect-devel
BuildRequires:  libjpeg-turbo-devel
BuildRequires:  libpcap-devel
BuildRequires:  libudev-devel
BuildRequires:  libusbx-devel
BuildRequires:  opencv-devel
BuildRequires:  openni-devel
BuildRequires:  pybind11-devel
BuildRequires:  ros-rolling-ament-cmake
BuildRequires:  ros-rolling-cv-bridge
BuildRequires:  ros-rolling-geometry-msgs
BuildRequires:  ros-rolling-nav-msgs
BuildRequires:  ros-rolling-octomap
BuildRequires:  ros-rolling-rclcpp
BuildRequires:  ros-rolling-ros-environment
BuildRequires:  ros-rolling-rosbag2-storage
BuildRequires:  ros-rolling-sensor-msgs
BuildRequires:  ros-rolling-std-msgs
BuildRequires:  ros-rolling-stereo-msgs
BuildRequires:  ros-rolling-tf2
BuildRequires:  ros-rolling-tf2-msgs
BuildRequires:  suitesparse-devel
BuildRequires:  tinyxml2-devel
BuildRequires:  wxGTK3-devel
BuildRequires:  zlib-devel
BuildRequires:  ros-rolling-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Mobile Robot Programming Toolkit (MRPT) version 2.x

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/rolling" \
    -DCMAKE_PREFIX_PATH="/opt/ros/rolling" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/rolling

%changelog
* Tue Jun 20 2023 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.9.2-2
- Autogenerated by Bloom

